export const _PENDING = '_PENDING';
export const _FULFILLED = '_FULFILLED';
export const _REJECTED = '_REJECTED';

export const CHANGE_ACCOUNT_BALANCE = 'CHANGE_ACCOUNT_BALANCE';
export const RESET_ACCOUNT_BALANCE = 'RESET_ACCOUNT_BALANCE';
export const FETCH_LAST_PRICE = 'FETCH_LAST_PRICE';
